refactor: now using vite app with libraries

diff --git a/.husky/pre-commit b/.husky/pre-commit
--- a/.husky/pre-commit
+++ b/.husky/pre-commit
@@ -4,46 +4,34 @@
 echo '🏗️👷 Styling, testing and building your project before committing'
 
 # Check Prettier standards
-npm run check-format ||
+pnpm check-format ||
 (
-        echo '🤢🤮🤢🤮 Its F**KING RAW - Your styling looks disgusting. 🤢🤮🤢🤮
-                Prettier Check Failed. Run npm run format, add changes and try commit again.';
-        false;
+  echo '🤢🤮🤢🤮 Its F**KING RAW - Your styling looks disgusting. 🤢🤮🤢🤮
+    Prettier Check Failed. Run pnpm format, add changes and try commit again.';
+  false;
 )
 
 # Check ESLint Standards
-npm run check-lint ||
+pnpm check-lint ||
 (
-        echo '😤🏀👋😤 Get that weak s**t out of here! 😤🏀👋😤 
-                ESLint Check Failed. Make the required changes listed above, add changes and try to commit again.'
-        false; 
+  echo '😤🏀👋😤 Get that weak s**t out of here! 😤🏀👋😤 
+    ESLint Check Failed. Make the required changes listed above, add changes and try to commit again.'
+  false; 
 )
 
 # Check tsconfig standards
-npm run check-types ||
+pnpm check-types ||
 (
-        echo '🤡😂❌🤡 Failed Type check. 🤡😂❌🤡
-                Are you seriously trying to write that? Make the changes required above.'
-        false;
+  echo '🤡😂❌🤡 Failed Type check. 🤡😂❌🤡
+    Are you seriously trying to write that? Make the changes required above.'
+  false;
 )
 
-# If everything passes... Now we can commit
-echo '🤔🤔🤔🤔... Alright... Code looks good to me... Trying to test and build now. 🤔🤔🤔🤔'
-
-npm run test ||
+pnpm build ||
 (
-        echo '❌👷🔨❌ Better call Irshad... Because your test failed ❌👷🔨❌
-                React test failed: View the errors above to see why. 
-        '
-        false;
-)
-
-npm run build ||
-(
-        echo '❌👷🔨❌ Better call Irshad... Because your build failed ❌👷🔨❌
-                React build failed: View the errors above to see why. 
-        '
-        false;
+  echo '❌👷🔨❌ Better call Irshad... Because your build failed ❌👷🔨❌
+    React build failed: View the errors above to see why.'
+  false;
 )
 
 # If everything passes... Now we can commit
